### ISSUE TITLE
Exception when I run this project: The getter '_store' was called on null.

### ISSUE THREAD

**Issue by petnagy** [Cretezy/redux_persist#5]
Hello,

I copied your example and when it start it throws an exception: 
I/flutter (26980): The following NoSuchMethodError was thrown building StoreConnector<AppState, String>(dirty):
I/flutter (26980): The getter '_store' was called on null.
I/flutter (26980): Receiver: null
I/flutter (26980): Tried calling: _store

If I comment out persistor.start(store); than it is running but there is nothing on the screen.

**Comment by petnagy** [comment]
Additional information it is working with redux_persist: ^0.4.0

**Comment by Cretezy** [comment]
Try a newer version, like 0.6.0. I think this was a bug in 0.4.0.

**Comment by ooasis** [comment]
This is likely related to https://github.com/brianegan/flutter_redux/issues/30#issuecomment-377507358

Can this project be updated with latest release of redux & flutter_redux (0.5.0)?

**Comment by Cretezy** [comment]
Alright, working on upgrading to the latest dependencies. Except a new version today.

**Comment by Cretezy** [comment]
Try out the new RCs:

* https://pub.dartlang.org/packages/redux_persist/versions/0.7.0-rc.1
* https://pub.dartlang.org/packages/redux_persist_flutter/versions/0.6.0-rc.1

This should work as intended. Let me know of any issues you run into.

**Comment by petnagy** [comment]
Thanks I will try it.

**Comment by Cretezy** [comment]
@petnagy How is the RCs working?

**Comment by petnagy** [comment]
@Cretezy thanks, it seems me ok. It is working for me!
